//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientMedicalHistoryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllergyHistory
    {
        public int AllergyID { get; set; }
        public string Allergen { get; set; }
        public string AllergyDescription { get; set; }
        public int C_PatientID { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
