//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientMedicalHistoryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientHistory
    {
        public int MedicalHistoryID { get; set; }
        public string DiseaseHistory { get; set; }
        public string SurgeryHistory { get; set; }
        public string MenstrualHistory { get; set; }
        public int C_PatientID { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
